infrastructureServices:
  - name: "RepositoryService"
    url: "https://repo.example.org/test/repository.git"
    usernameSecret: "repositoryUsername"
    passwordSecret: "repositoryPassword"
  - name: "SpecialGitService"
    url: "https://repo2.example.org/test2/other-repository.git"